// <auto-generated />
using System;
using MachineManagementSystemVer2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineManagementSystemVer2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922064523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CaseComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CaseComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("CasePhotoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CommentId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CasePhotoId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CaseComments");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CaseHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RepairCaseId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RepairCaseId");

                    b.ToTable("CaseHistories");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CasePhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("PhotoData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PhotoId");

                    b.HasIndex("CaseId");

                    b.ToTable("CasePhotos");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CustomerTaxId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerAddress = "台南市新市區",
                            CustomerName = "T公司",
                            CustomerPhone = "06-111-2222",
                            CustomerTaxId = "12345678"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerAddress = "台北市",
                            CustomerName = "發哥",
                            CustomerPhone = "06-111-2233",
                            CustomerTaxId = "11223344"
                        });
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("ProductionLine")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Remark")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeviceId");

                    b.HasIndex("PlantId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            DeviceModel = "NXE3400",
                            PlantId = 1,
                            ProductionLine = "H1#1",
                            SerialNumber = "20240901-001"
                        },
                        new
                        {
                            DeviceId = 2,
                            DeviceModel = "NXE3400",
                            PlantId = 2,
                            ProductionLine = "N1#1",
                            SerialNumber = "20240901-002"
                        },
                        new
                        {
                            DeviceId = 3,
                            DeviceModel = "ASM9000",
                            PlantId = 3,
                            ProductionLine = "RC1#1",
                            SerialNumber = "20240901-010"
                        });
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeePhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EmployeeTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b24ad0f5-e4b0-4d31-9084-8296a902d8d0",
                            EmailConfirmed = true,
                            EmergencyContact = "王媽媽",
                            EmergencyPhone = "0987654321",
                            EmployeeAddress = "屏東市xxxxxxxxx",
                            EmployeeId = 0,
                            EmployeeName = "王小明",
                            EmployeePhone = "0912345678",
                            EmployeeTitle = "現場工程師",
                            HireDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEHaISePi5c5r0js6rEv746LIDZZNonnUuHQdJ/xiqlUtIQ44jcIFin6bLVQakCYLmw==",
                            PhoneNumberConfirmed = false,
                            Role = "Engineer",
                            SecurityStamp = "6a5097dc-c62e-4745-8968-7866ce924ad8",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9862ab1-8b5e-4d39-a7c6-c5c5cc43d02f",
                            EmailConfirmed = true,
                            EmergencyContact = "李妻",
                            EmergencyPhone = "03-1234567",
                            EmployeeAddress = "新竹市xxxxxx",
                            EmployeeId = 0,
                            EmployeeName = "李主管",
                            EmployeePhone = "0952368741",
                            EmployeeTitle = "業務經理",
                            HireDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAELBxqYphOpmupvM8LU3qTTJE0Dwj8Xptt3KqrriK4T93ClkJCO6s5QUcDPj7flk6vw==",
                            PhoneNumberConfirmed = false,
                            Role = "Manager",
                            SecurityStamp = "2aca54cb-16b7-4a04-94bc-3a9cd719130d",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb04264f-4281-41d1-8a63-4e222ff66628",
                            EmailConfirmed = true,
                            EmergencyContact = "陳媽媽",
                            EmergencyPhone = "0987654321",
                            EmployeeAddress = "高雄市xxxxxxxxx",
                            EmployeeId = 0,
                            EmployeeName = "陳大華",
                            EmployeePhone = "0919874585",
                            EmployeeTitle = "現場工程師",
                            HireDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEFe9ZV1dS3La+ZFQPQk1Kg5m6LAH8OPKJ7HThN67xesCyrvun1q+ffD1fu/dKmBFXQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Engineer",
                            SecurityStamp = "3a4d66d2-ee2e-4739-a965-e517c91d8a72",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b81e8e0a-9903-4b0d-94c4-ed60d0116964",
                            EmailConfirmed = true,
                            EmergencyContact = "張嬸",
                            EmergencyPhone = "0987612587",
                            EmployeeAddress = "苗栗市xxxxxxxxx",
                            EmployeeId = 0,
                            EmployeeName = "張經理",
                            EmployeePhone = "0987258678",
                            EmployeeTitle = "工程部經理",
                            HireDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MANAGER2",
                            PasswordHash = "AQAAAAIAAYagAAAAENss9L3Yr0RQpbxcD5rJgfHfuoMGRa9wTuV73LA9UV0znxlRLqUsA21kfRvaxwY8AQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Manager",
                            SecurityStamp = "52af3223-b5e3-436e-bf25-db3a6d376088",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "manager2"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f57484b0-ecc8-476e-b25d-125cb487f7c3",
                            EmailConfirmed = true,
                            EmergencyContact = "工程師",
                            EmergencyPhone = "0987612587",
                            EmployeeAddress = "高雄市xxxxxxxxx",
                            EmployeeId = 0,
                            EmployeeName = "系統管理員",
                            EmployeePhone = "0987888888",
                            EmployeeTitle = "系統管理員",
                            HireDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuK4w/jBaCX+mLYldfpi8LtIW2yTilVKWU9fRzQbTwv4SIGw1GtZwoEwZUAZ5kRdA==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "1e2e6d1c-7244-49cc-bcf3-e449cb32584a",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "092cdefa-eb1e-427f-b29f-075827c69488",
                            EmailConfirmed = true,
                            EmergencyContact = "母",
                            EmergencyPhone = "0933333333",
                            EmployeeAddress = "高雄市",
                            EmployeeId = 0,
                            EmployeeName = "LJB",
                            EmployeePhone = "0911111111",
                            EmployeeTitle = "系統管理員",
                            HireDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "ABC",
                            PasswordHash = "AQAAAAIAAYagAAAAEPTe4HjFrl2IaveayVAZK/kFTEgMTk0LuqtdkP5pv/8tlq61MRUal9QELdLgSG7uMw==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "5eb14070-97ab-4f5c-b9f7-d59b5037ea6b",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "abc"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e1ffd323-65ba-45f2-bdf2-c441b2d2ab7d",
                            EmailConfirmed = true,
                            EmergencyContact = "人資測試",
                            EmergencyPhone = "0925856324",
                            EmployeeAddress = "高雄市oooooooo",
                            EmployeeId = 0,
                            EmployeeName = "林人資",
                            EmployeePhone = "0912365852",
                            EmployeeTitle = "人資",
                            HireDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "HR_USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEKkmGGD8su8hIIEE6WVeMGy7qwHLSQOm6W8UFuLnQUw73cf4wAAB9oRQa6mrD2Qemg==",
                            PhoneNumberConfirmed = false,
                            Role = "HR",
                            SecurityStamp = "bb1545c8-8554-42a6-bd60-5cda590c9e75",
                            Status = "在職",
                            TwoFactorEnabled = false,
                            UserName = "hr_user"
                        });
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PlantAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlantPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PlantId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            CustomerId = 1,
                            PlantAddress = "新竹市xoxox",
                            PlantCode = "H1",
                            PlantName = "新竹廠",
                            PlantPhone = "03-1224545"
                        },
                        new
                        {
                            PlantId = 2,
                            CustomerId = 1,
                            PlantAddress = "台南市xoxox",
                            PlantCode = "N1",
                            PlantName = "台南廠",
                            PlantPhone = "06-6548452"
                        },
                        new
                        {
                            PlantId = 3,
                            CustomerId = 2,
                            PlantAddress = "新竹縣xoxox",
                            PlantCode = "RC1",
                            PlantName = "竹科研發中心",
                            PlantPhone = "03-2116555"
                        });
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.RepairCase", b =>
                {
                    b.Property<int>("RepairCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairCaseId"));

                    b.Property<string>("CaseRemark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RepairCaseId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PlantId");

                    b.ToTable("RepairCases");

                    b.HasData(
                        new
                        {
                            RepairCaseId = 1,
                            CaseStatus = "OPEN",
                            Description = "客戶反應光刻機曝光後晶圓良率降低，需要檢查光源模組",
                            DeviceId = 1,
                            EmployeeId = "1",
                            OccurredAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantId = 1,
                            Title = "光刻機光源模組檢查"
                        },
                        new
                        {
                            RepairCaseId = 2,
                            CaseStatus = "暫置",
                            Description = "蝕刻腔體真空無法維持，懷疑是真空幫浦老化",
                            DeviceId = 2,
                            EmployeeId = "2",
                            OccurredAt = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantId = 2,
                            Title = "蝕刻腔體真空度異常"
                        },
                        new
                        {
                            RepairCaseId = 3,
                            CaseStatus = "CLOSE",
                            Description = "自動測試程式頻繁跳出錯誤代碼，需要檢查控制模組",
                            DeviceId = 3,
                            EmployeeId = "3",
                            OccurredAt = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantId = 3,
                            Title = "自動測試程式錯誤"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CaseComment", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.RepairCase", "RepairCase")
                        .WithMany("CaseComments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineManagementSystemVer2.Models.CasePhoto", "CasePhoto")
                        .WithMany()
                        .HasForeignKey("CasePhotoId");

                    b.HasOne("MachineManagementSystemVer2.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CasePhoto");

                    b.Navigation("Employee");

                    b.Navigation("RepairCase");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CaseHistory", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineManagementSystemVer2.Models.RepairCase", "RepairCase")
                        .WithMany("CaseHistories")
                        .HasForeignKey("RepairCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("RepairCase");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.CasePhoto", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.RepairCase", "RepairCase")
                        .WithMany("CasePhotos")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairCase");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Device", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Plant", "Plant")
                        .WithMany("Devices")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Plant", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Customer", "Customer")
                        .WithMany("Plants")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.RepairCase", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Customer", null)
                        .WithMany("RepairCases")
                        .HasForeignKey("CustomerId");

                    b.HasOne("MachineManagementSystemVer2.Models.Device", "Device")
                        .WithMany("RepairCases")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineManagementSystemVer2.Models.Employee", "Employee")
                        .WithMany("RepairCases")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineManagementSystemVer2.Models.Plant", "Plant")
                        .WithMany("RepairCases")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineManagementSystemVer2.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MachineManagementSystemVer2.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Customer", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("RepairCases");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Device", b =>
                {
                    b.Navigation("RepairCases");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Employee", b =>
                {
                    b.Navigation("RepairCases");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.Plant", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("RepairCases");
                });

            modelBuilder.Entity("MachineManagementSystemVer2.Models.RepairCase", b =>
                {
                    b.Navigation("CaseComments");

                    b.Navigation("CaseHistories");

                    b.Navigation("CasePhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
